# Generated by Django 5.0.7 on 2024-11-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="report_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
