# Generated by Django 5.0.7 on 2024-11-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_comment_report_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file_path",
            field=models.FileField(upload_to="videos_uploaded/"),
        ),
    ]
